CREATE TABLE e_mails_send(
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    hash TEXT NOT NULL UNIQUE,
    path TEXT NOT NULL,
    operated BOOLEAN NOT NULL DEFAULT FALSE,
    deleted BOOLEAN NOT NULL  DEFAULT FALSE
);

CREATE TABLE e_mails_inbox(
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    hash TEXT NOT NULL UNIQUE,
    content TEXT NOT NULL UNIQUE,
    operated BOOLEAN NOT NULL DEFAULT FALSE,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);